### ISSUE TITLE
clarify stage 3 and 4 entrance criteria around editor approval

### ISSUE THREAD

**Issue by michaelficarra** [tc39/process-document#19]
Now that we have an editor group instead of a single editor, I am unsure whether every member of that group must approve spec text (in the case of stage 3 entrance) or pull requests (in the case of stage 4 entrance). Are we to assume that any member of the editor group always speaks for the group?

Also, in the case of editor changes, does the approval of someone who was the editor at the time of the approval count as editor approval? What about approval of someone who was not the editor at the time of approval but is now the editor or a member of the editor group? I ask this not simply to explore the theoretical dilemmas but because I have already run into this with one of my proposals. And given we now have an editor group, I expect editor role changes to be more common than they were in the past.

Mentions of current and former editors for their input: @allenwb @bterlson @ljharb @bmeck

**Comment by michaelficarra** [comment]
Ping @ljharb @bterlson @bmeck. Do you have a regular editor group meeting at which this can be clarified? I don't think it's worth bringing in front of the committee.

**Comment by ljharb** [comment]
We do have a regular meeting, but schedule conflicts have popped up this and last week; this (very important) question is planned to be answered prior to the meeting.
