### ISSUE TITLE
Proposal repo should be a requirement

### ISSUE THREAD

**Issue by hax** [tc39/process-document#24]
Continue the discussion in https://github.com/tc39/proposals/issues/236

From @mathiasbynens 
> ...having a repository should be a requirement, even for stage 1. I'd go even further and claim that every feature proposal that is presented to TC39 needs a repository of which the README addresses the requirements outlined in the process doc.

From @ljharb
> If someone thinks a repo should be a requirement, an issue or PR to the process document is appropriate, but not here :-)

So I create this issue. 😀

**Comment by ljharb** [comment]
Seems like a PR, and an agenda item to get consensus on it, is in order.

**Comment by littledan** [comment]
I believe we've been treating this as a requirement in practice already, and have held things back at Stage 0 due to not having a proposal repo. Documenting our practices here makes sense to me.

**Comment by ljharb** [comment]
That's not been my experience. What have we held back for not having a repo?

(note that there are stage 1 proposals lacking a repo that were added in July 2019, July 2017, and September 2016)

**Comment by littledan** [comment]
My mistake then!

**Comment by codehag** [comment]
I think this is a good idea, as it will make our conversations stronger. Let's document this convention and also add it to the agenda template.

**Comment by ljharb** [comment]
Got consensus on this today; #26 is merged.
