### ISSUE TITLE
Dates of feature freeze for each version of specification

### ISSUE THREAD

**Issue by chicoxyzzy** [tc39/process-document#7]
Are there any dates of feature freeze? It'll be helpful to add this info to Process Document.

All I found is that

> TC39 may submit for approval to the Ecma General Assembly a new Edition of the ECMAScript language in March and September of every year. Additions which have been accepted by the committee as “finished” (stage 4) may be included in a new Edition.

But it's not clear what's happening on March and on September.

**Comment by allenwb** [comment]
see first few slides of https://github.com/tc39/tc39-notes/blob/master/es6/2015-01/jan2015-allen-slides.pdf

**Comment by ecmageneva** [comment]
Well,
this means that anything that is finished by TC39 can go twice a year for Ecma General Assembly (which are always in June and in December) approval. In practice so far TC39 used the March TC39 approval and the following June GA approval. Basically on the specs that were approved by TC39 in March no further work is done, but work on anything else which is for later TC39 and GA approval work can be processed.  
Kind regards, 
Istvan

**Comment by bterlson** [comment]
I have updated the [process document](http://tc39.github.io/process-document/) under the Spec Revisions and Scheduling heading. Please let me know any thoughts (or just submit a PR to fix it).

**Comment by chicoxyzzy** [comment]
Just to clarify, January meeting is a last chance for stage 3 proposals to be promoted to stage 4 and get into ES2017 right?

**Comment by bterlson** [comment]
@chicoxyzzy Correct, although November would be better for huge features...

**Comment by ctcpip** [comment]
I believe we have clarity on this these days, with approval of the yearly standards.  It's also not of much consequence, as ECMA-262 and ECMA-402 are living standards.
