### ISSUE TITLE
Number of maturity stages

### ISSUE THREAD

**Issue by chicoxyzzy** [tc39/process-document#8]
Quote from Process Document

> There are four “maturity” stages. The TC39 committee must approve acceptance for each stage.

After these sentences goes table named Maturity Stages which has 5 rows from Stage 0 to Stage 4.

It's not clear if first sentence above should be 

> There are five “maturity” stages.

or there should be a note that there are four maturity stages and Strawman stage

**Comment by ljharb** [comment]
The implication to me is that the fifth is simply not a maturity stage - namely Stage 0, where TC39 doesn't "approve" acceptance. The table name is perhaps not accurate.
